apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-bonus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab-gitlab-shell.gitlab.svc.cluster.local:root/inception-of-things-bonus.git
    targetRevision: main
    path: p3/confs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true