global:
  hosts:
    domain: 127.0.0.1.nip.io
  ingress:
    configureCertmanager: false 
    tls:
      enabled: false
    enabled: true
    provider: generic
    class: none
  edition: ce

certmanager:
  enabled: false
certmanager-issuer:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
nginx-ingress:
  enabled: false

kas:
  enabled: false
registry:
  enabled: false
gitlab-exporter:
  enabled: false

gitlab:
  webservice:
    replicas: 1
    minReplicas: 1
    hpa:
      enabled: false
    resources:
      requests:
        memory: 1.5Gi
        cpu: 200m

  sidekiq:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    hpa:
      enabled: false
    resources:
      requests:
        memory: 450Mi
        cpu: 100m

  gitlab-shell:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    hpa:
      enabled: false
    resources:
      requests:
        memory: 64Mi
        cpu: 50m

postgresql:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

redis:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"

minio:
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"