Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20240821.0.1"

  config.vm.define "kbrener-S" do |machine|
    machine.vm.network "private_network", ip: "192.168.56.110"
    machine.vm.hostname = "kbrener-S"
    config.vm.provider "virtualbox" do |machine|
      machine.gui = true
      machine.memory = "2042"
      machine.cpus = 1
    end
    machine.vm.provision "shell", path: "setup.sh"
  end
end