Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20240821.0.1"

  config.vm.define "dabaeSW" do |worker|
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.hostname = "dabaeSW"
    config.vm.provider "virtualbox" do |machine|
      machine.gui = true
      machine.memory = "1024"
      machine.cpus = 1
    end
    worker.vm.provision "shell", path: "setup-worker.sh"
  end
  
  config.vm.define "dabaeS" do |control|
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.hostname = "dabaeS"
    config.vm.provider "virtualbox" do |machine|
      machine.gui = true
      machine.memory = "1024"
      machine.cpus = 1
    end
    control.vm.provision "shell", path: "setup-controller.sh"
  end
end