Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.synced_folder ".", "/vagrant",
    type: "virtualbox",
    owner: "vagrant",
    group: "vagrant"
    
  config.vm.define "dabaeS" do |control|
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.hostname = "dabaeS"
    control.vm.provider "virtualbox" do |machine|
      machine.memory = "1024"
      machine.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/setup-controller.sh"
  end
  config.vm.define "dabaeSW" do |worker|
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.hostname = "dabaeSW"
    worker.vm.provider "virtualbox" do |machine|
      machine.memory = "1024"
      machine.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/setup-worker.sh"
  end
end