Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.disk :disk, size: "70GB", primary: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "12288"
    vb.cpus = 8
    vb.name = "GitLab-Server-Ubuntu2404"
    
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl openssh-server ca-certificates perl vim make
    if [ ! -f /swapfile ]; then
      fallocate -l 4G /swapfile
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
    fi
    if [ -b /dev/mapper/ubuntu--vg-ubuntu--lv ]; then
      lvextend -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv
      resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
    fi
  SHELL
end